src/Entity/Message.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessageRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Message
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Ce message n'existe pas !", allowNull=True)
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur", inversedBy="messages")
     * @ORM\JoinColumn(name="auteur_id", referencedColumnName="id",onDelete="SET NULL",nullable=true)
     */
    private $auteur;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateCreation;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="message")
     */
    private $commentaires;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $IsArchived;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Personnel", inversedBy="messages")
     * @ORM\JoinColumn(name="signature_id", referencedColumnName="id",onDelete="SET NULL",nullable=true)
     */
    private $Signature;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ip;

    

    /**
     * @ORM\PrePersist
     */
    public function prePersist()
    {
        if(empty($this->dateCreation)){
            $this->dateCreation = new \DateTime();
        }
    }

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getAuteur(): ?Utilisateur
    {
        return $this->auteur;
    }

    public function setAuteur(?Utilisateur $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setMessage($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getMessage() === $this) {
                $commentaire->setMessage(null);
            }
        }

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getIsArchived(): ?bool
    {
        return $this->IsArchived;
    }

    public function setIsArchived(bool $IsArchived): self
    {
        $this->IsArchived = $IsArchived;

        return $this;
    }

    public function getSignature(): ?Personnel
    {
        return $this->Signature;
    }

    public function setSignature(?Personnel $Signature): self
    {
        $this->Signature = $Signature;

        return $this;
    }

    public function getIp(): ?string
    {
        return $this->ip;
    }

    public function setIp(string $ip): self
    {
        $this->ip = $ip;

        return $this;
    }


   
}

src/Controller/CommunicationController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\MessageRepository;
use App\Repository\CommentaireRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Annotation\Route;

// Include paginator interface
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CommunicationController extends AbstractController
{
    /**
     * @Route("/communication", name="communication")
     * @IsGranted("ROLE_USER")
     */
    public function liste(MessageRepository $repo_message, PaginatorInterface $paginator, Request $request)
    {
         // Retrieve the entity manager of Doctrine
         $em = $this->getDoctrine()->getManager();
        
         // Get some repository of data, in our case we have an Appointments entity
         $repo_message = $em->getRepository(Message::class);
                 

        // Find all the data on the Appointments table, filter your query as you need
        $allMessagesQuery = $repo_message->createQueryBuilder('m')
            ->where('m.IsArchived = false')
            ->orderBy('m.dateCreation', 'DESC')
            ->getQuery();
        
        // Paginate the results of the query
        $messages = $paginator->paginate(
            // Doctrine Query, not results
            $allMessagesQuery,
            // Define the page parameter
            $request->query->getInt('page', 1),
            // Items per page
            5
        );

        return $this->render('communication/liste.html.twig',[
            'messages'=> $messages
        ]);
    }

   

    /**
     * @Route("/communication/message/{id}", name="afficher_message")
     * @IsGranted("ROLE_USER")
     */
    public function afficherMessage($id, MessageRepository $repo_mess, CommentaireRepository $repo_comm, Request $request, EntityManagerInterface $manager)
    {
        
        $message= $repo_mess->find($id);
        $commentaires= $repo_comm->findAll(); /* Récupère un message spécifique (via l'Id) dans la table concernée ainsi que les commentaires liés */
        
        $commentaire = new Commentaire();

        $ip = $request->getClientIp();

        $form = $this->createForm(CommentaireType::class, $commentaire); /* Crée le formulaire Symfony de création de commentaire */

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){ /* Vérification du formulaire soumis par l'utilisateur */

            $commentaire->setDateCreation(new \DateTime()); /* Ajout automatique de la date/heure de création du commentaire*/
            $commentaire->setMessage($message); /* Permet de lier le commentaire crée au message affiché*/
            $commentaire->setAuteur($this->getUser()); /* Définit l'utilisateur connecté en tant qu'auteur */
            $commentaire->setIp($ip);
            
            $manager->persist($commentaire);
            $manager->flush();

            $this->addFlash(
                'success',
                "Le commentaire a bien été enregistré !"
            );
           
            return $this->redirectToRoute('afficher_message',[
                'id'=> $message->getId()
            ]);
        }

        return $this->render('communication/message.html.twig',[
            'message' => $message,
            'commentaires' => $commentaires,
            'form' => $form->createView()
        ]);

    }

}

templates/communication/archives.html.twig
{% extends "base.html.twig" %}

{% block title %}Archives{% endblock title %}

{% block body %}
<div class="container text-center">
    <div>
        <h1>Archives</h1>
        <a href="{{path('communication')}}" class="btn btn-warning btn-lg">Consulter les messages publics</a>
    </div>

    {% for message in messages %}
        
    <div class="container message mt-2" {% if message.auteur.roles[0]|default('') == 'ROLE_ADMIN' %} style="background-color: gold" {% endif %}>

        {% if is_granted('ROLE_ADMIN') %}
        
        <a href="{{path('admin_message_supprimer', {id: message.id})}}" class="btn btn-danger" style="float: right">Supprimer</a>

        {% endif %}

        <h3>{{message.titre}}</h3> 
        <p>{{message.contenu|raw}}</p>

        <div>                  
            <p>Ecrit par <span style="font-weight:bold"> 
                {% if message.auteur.roles[0]|default('') == 'ROLE_ADMIN' %}
                    {{message.auteur.nom|default('Utilisateur supprimé')}}
                {% else %} 
                    {{message.signature.nom|default('Utilisateur supprimé')}}
                {% endif %}
            </span>, le {{message.dateCreation|date("d/m/Y H:i" )}}
            </p>
        </div>
        <a href="{{path('afficher_message_archives', {id: message.id})}}" class="btn btn-primary">En savoir plus</a>  
    </div>  

    {% endfor %}  
    <div class="navigation mt-2 pagination ">
        {{ knp_pagination_render(messages) }}
    </div>
</div>
{% endblock body %}

templates/communication/liste.html.twig
{% extends 'base.html.twig' %}

{% block title %}Communication{% endblock %}

{% block body %}
<div class="container text-center">
    <div>
        <h1>Communication</h1>
        <a href="{{path('creer_message')}}" class="btn btn-success btn-lg">Ecrire un nouveau message</a>
        
        {#-------------------Permet d'afficher un bouton si connecté en Admin---------------#}
        {% if is_granted('ROLE_ADMIN') %}
        <a href="{{path('archives')}}" class="btn btn-warning btn-lg">Consulter les archives</a>
        {% endif %}
        {#----------------------------------------------------------------------------------#}
    </div>

    {% for message in messages %}
        
    <div class="container message mt-2" {% if message.auteur.roles[0]|default('') == 'ROLE_ADMIN' %} style="background-color: gold" {% endif %}>
        
        {% if is_granted('ROLE_ADMIN') %}
            
        <a href="{{path('admin_editer_message', {id: message.id})}}" class="btn btn-success" style="float: right">Editer</a>

        {% endif %}
        <h3>{{message.titre}}</h3> 
        
        <p>{{message.contenu}}</p>
        <div>                  
            <p>Ecrit par <span style="font-weight:bold">
                {% if message.auteur.roles[0]|default('') == 'ROLE_ADMIN' %}
                    {{message.auteur.nom|default('Utilisateur supprimé')}}
                {% else %} 
                    {{message.signature.nom|default('Utilisateur supprimé')}}
                {% endif %}
                </span>, le {{message.dateCreation|date("d/m/Y H:i" )}}
            </p>
        </div>
        <a href="{{path('afficher_message', {id: message.id})}}" class="btn btn-primary">En savoir plus ({{message.commentaires|length}} commentaire(s))</a>  
    </div>  

    {% endfor %}  

    <div class="navigation mt-2 pagination" >
        {{ knp_pagination_render(messages) }}
    </div>

</div>
{% endblock %}

templates/communication/message.html.twig
{% extends "base.html.twig" %}

{% block title %}Afficher un message{% endblock title %}

{% block body %}


{% if message.Isarchived == true and not is_granted('ROLE_ADMIN') %}

<h1 class="text-center mt-5"> Vous n'avez pas accès à ce message car il est archivé !</h1>

{% else %}
    

<div class="container">
        {% if is_granted('ROLE_ADMIN') %} {#---Connexion en admin obligatoire en tant que condition---#}

    {#-------------------------------------Afficher le bouton Archiver ou Désarchiver en fonction de l'état du message------------------------#}
    <div class="text-center">
        {% if message.IsArchived == true %}
        <a href="{{path('desarchiver_message', {id: message.id})}}" class="btn btn-danger btn-lg my-3">Désarchiver le message</a>
        {% else %}
        <a href="{{path('archiver_message', {id: message.id})}}" class="btn btn-danger btn-lg my-3">Archiver le message</a>
        {% endif %}
    </div>
    {#----------------------------------------------------------------------------------------------------------------------------------------#}

    {% endif %}

    <div class="row" style="justify-content:space-between">
        {% if message.IsArchived == false %}
        <div class="col-6" style="display: flex; justify-content:flex-start">
            <a href="{{path('communication')}}" class="btn btn-success btn-lg">Retour</a>
        </div>
        {% if message.auteur.id|default('Utilisateur supprimé') == app.user.id %}
            
        <div class="col-6" style="display: flex; justify-content:flex-end">
            <a href="{{path('editer_message', {id: message.id})}}" class="btn btn-success btn-lg">Editer le message</a>
        </div>
        {% endif %}
        
        {% else %}
        <a href="{{path('archives')}}" class="btn btn-success btn-lg">Retour</a>
        {% endif %}
    </div>
</div>

{#----------------------------------Affichage du message-------------------------------------#}

<div class="container message mt-2 text-center" {% if message.auteur.roles[0]|default('') == 'ROLE_ADMIN' %} style="background-color: gold" {% endif %}>
    <div class="">
       <h3>{{message.titre}}</h3> 
    </div>
    <p>{{message.contenu|raw}}</p>
    <div>                  
        <p>Ecrit par <span style="font-weight:bold">

            {% if message.auteur.roles[0]|default('') == 'ROLE_ADMIN' %}
                {{message.auteur.nom|default('Utilisateur supprimé')}}
            {% else %} 
                {{message.signature.nom|default('Utilisateur supprimé')}}
            {% endif %}
            
            </span>, le {{message.dateCreation|date("d/m/Y H:i" )}}
        </p>
    </div>  
</div>

{#------------------------------Affichage des commentaires-----------------------------------#}
    
<div id="commentaire-liste" class="container">
    {% for commentaire in message.commentaires %}
    
    <div class="bg-commentaire mt-2 commentaire-bloc" {% if commentaire.auteur.roles[0]|default('') == 'ROLE_ADMIN' %} style="background-color: gold" {% endif %} >
        <div>
                {% if commentaire.auteur.id|default('Utilisateur supprimé') == app.user.id  %}

                <a href="{{path('editer_commentaire', {id: commentaire.id})}}" class="btn btn-success" style="float: right">Editer</a>
                
                {% else %}

                <a href="{{path('admin_editer_commentaire', {id: commentaire.id})}}" class="btn btn-success" style="float: right">Editer</a>

                {% endif %}

            <p>  {{commentaire.contenu|raw}} </p>
        </div>
        <div>
            <p>Ecrit par <span style="font-weight:bold">

                {% if commentaire.auteur.roles[0]|default('') == 'ROLE_ADMIN' %}
                    {{commentaire.auteur.nom|default('Utilisateur supprimé')}}
                {% else %} 
                    {{commentaire.signature.nom|default('Utilisateur supprimé')}}
                {% endif %}
                
                </span>, le {{commentaire.dateCreation|date("d/m/Y H:i" )}}
            </p>
        </div>
    </div>
    {% endfor %}
</div>

{#-------------------------Formulaire de création de commentaire----------------------------#}

<div class="container mt-5">
    <h1 class="text-center">Nouveau commentaire</h1>

    {{form_start(form)}}
    {{form_widget(form)}}
    <div class="text-center">
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </div>
    {{form_end(form)}}
    
</div>

{% endif %}
{% endblock body %}